
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lee-PC
 */

//jdbc:mysql://localhost:3306/17312296_firliafrisa_inventaris

public class MasterBarang extends javax.swing.JFrame {

    /**
     * Creates new form MasterBarang
     */
    
    Connection c;
    ResultSet r;
    Statement s;
    private Object[][]databarang=null;
    private String[] label={"Kode Barang",
        "Nama Barang","Merk",
        "Serial Number","Tanggal Beli","Stok"};
  
    
    
    
    
    public MasterBarang() {
        initComponents();
        koneksi();
        bacatabeldata();
        setawal();
        
        txt_kd.requestFocus();
        
    }

    
    
    private void koneksi(){
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/17312296_firliafrisa_inventaris","root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            
            System.out.println("Koneksi Gagal"+ e);
        }
        
        
    }
    
    private void bacatabeldata(){
    try {
            s=c.createStatement();
            String sql="Select * From barang Order By kd_barang";
            r=s.executeQuery(sql);
            ResultSetMetaData m=r.getMetaData();
            int kolom=m.getColumnCount();
            int baris=0;
            while(r.next()){
                baris=r.getRow();
            }
            databarang=new Object[baris][kolom];
            int x=0;
            r.beforeFirst();
            while(r.next()){
                databarang[x][0]=r.getString("kd_barang");
                databarang[x][1]=r.getString("nama_barang");
                databarang[x][2]=r.getString("merk");
                databarang[x][3]=r.getString("serialnumber");
                databarang[x][4]=r.getString("tgl_beli");
                databarang[x][5]=r.getString("stok");
                
                x++;
            }
            tabel_barang.setModel(new DefaultTableModel(databarang,label));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    
    }
    
    
    private void settabel(){
        int row=tabel_barang.getSelectedRow();
        txt_kd.setText((String)tabel_barang.getValueAt(row, 0));
        txt_brg.setText((String)tabel_barang.getValueAt(row, 1));
        txt_merk.setText((String)tabel_barang.getValueAt(row, 2));
        txt_sn.setText((String)tabel_barang.getValueAt(row, 3));
        txt_tgl.setText((String)tabel_barang.getValueAt(row, 4));
        txt_stok.setText((String)tabel_barang.getValueAt(row, 5));
            
    
    }
    
    private void setawal(){
    
        txt_kd.setText("");
        txt_brg.setText("");
        txt_merk.setText("");
        txt_sn.setText("");
        txt_stok.setText("");
        txt_tgl.setText("2019-04-11");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        txt_kd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_brg = new javax.swing.JTextField();
        txt_merk = new javax.swing.JTextField();
        txt_sn = new javax.swing.JTextField();
        txt_tgl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA BARANG");

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Merk", "Serial Number", "Tanggal Beli", "Stok"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        tabel_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabel_barangKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang);

        txt_kd.setText("jTextField1");
        txt_kd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kdKeyPressed(evt);
            }
        });

        jLabel2.setText("Kode Barang");

        txt_brg.setText("jTextField1");
        txt_brg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_brgKeyPressed(evt);
            }
        });

        txt_merk.setText("jTextField1");
        txt_merk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_merkKeyPressed(evt);
            }
        });

        txt_sn.setText("jTextField1");
        txt_sn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_snKeyPressed(evt);
            }
        });

        txt_tgl.setText("jTextField1");
        txt_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tglKeyPressed(evt);
            }
        });

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Merk");

        jLabel5.setText("Serial Number");

        jLabel6.setText("Tanggal Beli");

        jLabel7.setText("Stok");

        txt_stok.setText("jTextField1");
        txt_stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_stokKeyPressed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_Edit.setText("Edit");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_merk, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_kd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_simpan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_Edit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_hapus)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_keluar))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_merk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_Edit)
                            .addComponent(btn_keluar)
                            .addComponent(btn_hapus))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edittable(){
    
    try {
            String sql="Update barang Set kd_barang='"+txt_kd.getText()+"',nama_barang='"+txt_brg.getText()+"',merk='"+txt_merk.getText()
                    +"',serialnumber='"+txt_sn.getText()+"',tgl_beli='"+txt_tgl.getText()+"',stok='"+txt_stok.getText()+"'";
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(null, "data berhasil diedit");
            setawal();
            bacatabeldata();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void simpan(){
    
         try {
            String sql="Insert Into barang Values('"+txt_kd.getText()+"','"+txt_brg.getText()+"','"+txt_merk.getText()+"','"+txt_sn.getText()+"','"+txt_tgl.getText()+"','"+txt_stok.getText()+"')";
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            setawal();
            bacatabeldata();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    
    
    }
    
    
    
    private void hapus(){
        
        
        
        
          try {
            String sql="Delete from barang Where kd_barang='"+txt_kd.getText()+"'";
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
            setawal();
            bacatabeldata();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    
    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
       simpan();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        // TODO add your handling code here:
        
        edittable();
        
        
        
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabel_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_barangKeyPressed
        // TODO add your handling code here:
        settabel();
        
    }//GEN-LAST:event_tabel_barangKeyPressed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        // TODO add your handling code here:
        settabel();
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void txt_kdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) {
             txt_brg.requestFocus();
        }
        
       
    }//GEN-LAST:event_txt_kdKeyPressed

    private void txt_brgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brgKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyChar()==evt.VK_ENTER) {
             txt_merk.requestFocus();
        }
        
    }//GEN-LAST:event_txt_brgKeyPressed

    private void txt_merkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_merkKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==evt.VK_ENTER) {
             txt_sn.requestFocus();
        }
        
        
        
        
        
    }//GEN-LAST:event_txt_merkKeyPressed

    private void txt_snKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_snKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==evt.VK_ENTER) {
          txt_stok.requestFocus();
        }
        
    }//GEN-LAST:event_txt_snKeyPressed

    private void txt_stokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stokKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==evt.VK_ENTER) {
          txt_tgl.requestFocus();
        }
        
        
    }//GEN-LAST:event_txt_stokKeyPressed

    private void txt_tglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tglKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==evt.VK_ENTER) {
           txt_kd.requestFocus();
        }
      
    }//GEN-LAST:event_txt_tglKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTextField txt_brg;
    private javax.swing.JTextField txt_kd;
    private javax.swing.JTextField txt_merk;
    private javax.swing.JTextField txt_sn;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_tgl;
    // End of variables declaration//GEN-END:variables
}
